### ISSUE TITLE
Questions about missing files

### ISSUE THREAD

**Issue by Adeline929292** [vinbigdata-medical/vindr-spinexr#2]
I want to get the result of ensemble classification model. However, I can’t find the config file ‘densenet121_dgx3.yaml’ mentioned in the ‘ensemble.sh’. So How can I get the result?

**Comment by hieu1999210** [comment]
it should be densenet121.yaml. Any provided densenet*.yaml file should be fine since the ensemble scripts only need config of the dataset and path.
